const finite = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const clamp = (value, low, high) => Math.max(low, Math.min(high, value));

function pointInPolygon(x, y, points = []) {
  let inside = false;
  for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
    const xi = finite(points[i]?.[0]), yi = finite(points[i]?.[1]);
    const xj = finite(points[j]?.[0]), yj = finite(points[j]?.[1]);
    if ((yi > y) !== (yj > y) && x < (xj - xi) * (y - yi) / ((yj - yi) || Number.EPSILON) + xi) inside = !inside;
  }
  return inside;
}

function distanceToSegment(x, y, a, b) {
  const dx = finite(b?.[0]) - finite(a?.[0]); const dy = finite(b?.[1]) - finite(a?.[1]);
  const t = clamp(((x - finite(a?.[0])) * dx + (y - finite(a?.[1])) * dy) / (dx * dx + dy * dy || 1), 0, 1);
  return Math.hypot(x - (finite(a?.[0]) + t * dx), y - (finite(a?.[1]) + t * dy));
}

function featureContains(feature, x, y, depth) {
  if (depth < finite(feature.minDepth) || depth > finite(feature.maxDepth, Infinity)) return false;
  const points = feature.points || [];
  if (feature.model === "plume") {
    const center = points[0] || [0, 0];
    return Math.hypot(x - center[0], y - center[1]) <= finite(feature.semiMajorAxis, 70000);
  }
  if (feature.model === "subducting plate" || feature.model === "fault") {
    const width = Math.max(1, finite(feature.thickness, 90000) / 2);
    return points.slice(1).some((point, index) => distanceToSegment(x, y, points[index], point) <= width);
  }
  return points.length >= 3 && pointInPolygon(x, y, points);
}

function featureValues(features, x, y, depth, fallbackTemperature) {
  let temperature = fallbackTemperature; let composition = null;
  for (const feature of features || []) {
    if (!featureContains(feature, x, y, depth)) continue;
    const layer = (feature.layers || []).find(item => depth >= finite(item.minDepth) && depth <= finite(item.maxDepth));
    temperature = finite(layer?.temperature, finite(feature.temperature, temperature));
    composition = Math.max(0, Math.round(finite(layer?.composition, finite(feature.composition, 0))));
  }
  return { temperature, composition };
}

function axis(minimum, maximum, count) {
  const n = Math.max(2, Math.round(finite(count, 2)));
  return Array.from({ length: n }, (_, index) => minimum + index / (n - 1) * (maximum - minimum));
}

function coordinate(settings, x, y, depth, dimension) {
  if (settings.coordinateSystem !== "spherical") {
    const vertical = finite(settings.zMax) - depth;
    return dimension === 2 ? [x, vertical] : [x, y, vertical];
  }
  const radius = finite(settings.radius, 6371000) - depth;
  const phi = x * Math.PI / 180;
  const theta = (90 - y) * Math.PI / 180;
  return dimension === 2 ? [radius, phi] : [radius, phi, theta];
}

export function buildAspectAscii(settings, features, options = {}) {
  const dimension = Number(options.dimension || settings.dimension) === 3 ? 3 : 2;
  const nx = Math.max(2, Math.round(finite(options.nx, settings.cellsX + 1)));
  const ny = dimension === 3 ? Math.max(2, Math.round(finite(options.ny, settings.cellsY + 1))) : 1;
  const nz = Math.max(2, Math.round(finite(options.nz, settings.cellsZ + 1)));
  const xs = axis(finite(settings.xMin), finite(settings.xMax), nx);
  const ys = dimension === 3 ? axis(finite(settings.yMin), finite(settings.yMax), ny) : [finite(options.sectionY, (finite(settings.yMin) + finite(settings.yMax)) / 2)];
  const depths = axis(finite(settings.zMin), finite(settings.zMax), nz).reverse();
  const maximumComposition = Math.max(0, ...(features || []).flatMap(feature => [feature.composition, ...(feature.layers || []).map(layer => layer.composition)]).map(value => Math.round(finite(value))));
  const count = Math.max(1, maximumComposition + 1, Math.round(finite(options.compositions, settings.compositions)));
  if (nx * ny * nz > 2_000_000) throw new Error("ASPECT export is limited to 2,000,000 sample points in the browser. Reduce the sample counts.");
  const includeTemperature = options.temperature !== false;
  const includeComposition = options.composition !== false;
  const columns = [...(dimension === 2 ? ["x", "y"] : ["x", "y", "z"]), ...(includeTemperature ? ["temperature"] : []), ...(includeComposition ? Array.from({ length: count }, (_, i) => `composition_${i}`) : [])];
  const rows = [
    "# ASPECT structured ASCII data generated by GWB Visual Builder",
    `# POINTS: ${settings.coordinateSystem === "spherical" ? (dimension === 2 ? `${nz} ${nx}` : `${nz} ${nx} ${ny}`) : (dimension === 2 ? `${nx} ${nz}` : `${nx} ${ny} ${nz}`)}`,
    `# Columns: ${columns.join(" ")}`,
    `# Coordinates: ${settings.coordinateSystem === "spherical" ? (dimension === 2 ? "r phi (m, radians)" : "r phi theta (m, radians; theta is colatitude)") : "Cartesian metres"}`
  ];
  const write = (x, y, depth) => {
    const sampled = featureValues(features, x, y, depth, finite(settings.mantleTemperature, 1600));
    const values = coordinate(settings, x, y, depth, dimension);
    if (includeTemperature) values.push(sampled.temperature);
    if (includeComposition) for (let field = 0; field < count; field++) values.push(sampled.composition === field ? 1 : 0);
    rows.push(values.map(value => Number(value).toPrecision(12)).join(" "));
  };
  // ASPECT requires the first output coordinate to ascend fastest.
  if (settings.coordinateSystem === "spherical") {
    // Latitude must descend so ASPECT's polar angle theta ascends.
    for (const y of [...ys].reverse()) for (const x of xs) for (const depth of depths) write(x, y, depth);
  } else {
    for (const depth of depths) for (const y of ys) for (const x of xs) write(x, y, depth);
  }
  return `${rows.join("\n")}\n`;
}

export function buildAspectCompositionContours(features) {
  const rows = ["# feature_id feature_name composition layer_name min_depth_m max_depth_m vertex_index x y"];
  for (const feature of features || []) {
    const layers = feature.layers?.length ? feature.layers : [{ name: "feature", composition: feature.composition, minDepth: feature.minDepth, maxDepth: feature.maxDepth }];
    for (const layer of layers) for (let index = 0; index < (feature.points || []).length; index++) {
      const point = feature.points[index];
      rows.push([feature.id, JSON.stringify(feature.name || feature.model), Math.round(finite(layer.composition)), JSON.stringify(layer.name || "layer"), finite(layer.minDepth), finite(layer.maxDepth), index, finite(point[0]), finite(point[1])].join(" "));
    }
    rows.push("");
  }
  return `${rows.join("\n")}\n`;
}
